// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: protos/head.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectInfo_ObjectType int32

const (
	ObjectInfo_FILE      ObjectInfo_ObjectType = 0
	ObjectInfo_DIRECTORY ObjectInfo_ObjectType = 1
)

// Enum value maps for ObjectInfo_ObjectType.
var (
	ObjectInfo_ObjectType_name = map[int32]string{
		0: "FILE",
		1: "DIRECTORY",
	}
	ObjectInfo_ObjectType_value = map[string]int32{
		"FILE":      0,
		"DIRECTORY": 1,
	}
)

func (x ObjectInfo_ObjectType) Enum() *ObjectInfo_ObjectType {
	p := new(ObjectInfo_ObjectType)
	*p = x
	return p
}

func (x ObjectInfo_ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectInfo_ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_head_proto_enumTypes[0].Descriptor()
}

func (ObjectInfo_ObjectType) Type() protoreflect.EnumType {
	return &file_protos_head_proto_enumTypes[0]
}

func (x ObjectInfo_ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectInfo_ObjectType.Descriptor instead.
func (ObjectInfo_ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{2, 0}
}

// UUID message structure
type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetDirectoryContentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey string `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// The directory to get the contents of.
	// If not provided, HOME will be used.
	DirId *UUID `protobuf:"bytes,2,opt,name=dir_id,json=dirId,proto3" json:"dir_id,omitempty"`
}

func (x *GetDirectoryContentsRequest) Reset() {
	*x = GetDirectoryContentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirectoryContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryContentsRequest) ProtoMessage() {}

func (x *GetDirectoryContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryContentsRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoryContentsRequest) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{1}
}

func (x *GetDirectoryContentsRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *GetDirectoryContentsRequest) GetDirId() *UUID {
	if x != nil {
		return x.DirId
	}
	return nil
}

type ObjectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID and type of the object.
	ObjectId   *UUID                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ObjectType ObjectInfo_ObjectType `protobuf:"varint,2,opt,name=object_type,json=objectType,proto3,enum=hootfs.head.ObjectInfo_ObjectType" json:"object_type,omitempty"`
	ObjectName string                `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
}

func (x *ObjectInfo) Reset() {
	*x = ObjectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfo) ProtoMessage() {}

func (x *ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfo.ProtoReflect.Descriptor instead.
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectInfo) GetObjectId() *UUID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

func (x *ObjectInfo) GetObjectType() ObjectInfo_ObjectType {
	if x != nil {
		return x.ObjectType
	}
	return ObjectInfo_FILE
}

func (x *ObjectInfo) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

type GetDirectoryContentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*ObjectInfo `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *GetDirectoryContentsResponse) Reset() {
	*x = GetDirectoryContentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirectoryContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryContentsResponse) ProtoMessage() {}

func (x *GetDirectoryContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryContentsResponse.ProtoReflect.Descriptor instead.
func (*GetDirectoryContentsResponse) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{3}
}

func (x *GetDirectoryContentsResponse) GetObjects() []*ObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

type MakeDirectoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey string `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// This is the ID of the directory
	// the new directory will be created into.
	// If this is not provided, HOME will be used.
	DirId *UUID `protobuf:"bytes,2,opt,name=dir_id,json=dirId,proto3" json:"dir_id,omitempty"`
	// This is the name of the new directory.
	DirName string `protobuf:"bytes,3,opt,name=dir_name,json=dirName,proto3" json:"dir_name,omitempty"`
}

func (x *MakeDirectoryRequest) Reset() {
	*x = MakeDirectoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirectoryRequest) ProtoMessage() {}

func (x *MakeDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirectoryRequest.ProtoReflect.Descriptor instead.
func (*MakeDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{4}
}

func (x *MakeDirectoryRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *MakeDirectoryRequest) GetDirId() *UUID {
	if x != nil {
		return x.DirId
	}
	return nil
}

func (x *MakeDirectoryRequest) GetDirName() string {
	if x != nil {
		return x.DirName
	}
	return ""
}

type MakeDirectoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the directory created.
	DirId *UUID `protobuf:"bytes,1,opt,name=dir_id,json=dirId,proto3" json:"dir_id,omitempty"`
}

func (x *MakeDirectoryResponse) Reset() {
	*x = MakeDirectoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirectoryResponse) ProtoMessage() {}

func (x *MakeDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirectoryResponse.ProtoReflect.Descriptor instead.
func (*MakeDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{5}
}

func (x *MakeDirectoryResponse) GetDirId() *UUID {
	if x != nil {
		return x.DirId
	}
	return nil
}

type AddNewFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey string `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// ID of directory to place folder in.
	DirId *UUID `protobuf:"bytes,2,opt,name=dir_id,json=dirId,proto3" json:"dir_id,omitempty"`
	// Name of file to create.
	FileName string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// Contents of file being added...
	// If not provided, an empty file
	// will be created.
	Contents []byte `protobuf:"bytes,4,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *AddNewFileRequest) Reset() {
	*x = AddNewFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewFileRequest) ProtoMessage() {}

func (x *AddNewFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewFileRequest.ProtoReflect.Descriptor instead.
func (*AddNewFileRequest) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{6}
}

func (x *AddNewFileRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *AddNewFileRequest) GetDirId() *UUID {
	if x != nil {
		return x.DirId
	}
	return nil
}

func (x *AddNewFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AddNewFileRequest) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type AddNewFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the file created.
	FileId *UUID `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *AddNewFileResponse) Reset() {
	*x = AddNewFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewFileResponse) ProtoMessage() {}

func (x *AddNewFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewFileResponse.ProtoReflect.Descriptor instead.
func (*AddNewFileResponse) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{7}
}

func (x *AddNewFileResponse) GetFileId() *UUID {
	if x != nil {
		return x.FileId
	}
	return nil
}

type UpdateFileContentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey string `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	FileId     *UUID  `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// The given file's contents will be
	// set to contents.
	Contents []byte `protobuf:"bytes,3,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *UpdateFileContentsRequest) Reset() {
	*x = UpdateFileContentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFileContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileContentsRequest) ProtoMessage() {}

func (x *UpdateFileContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileContentsRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileContentsRequest) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFileContentsRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *UpdateFileContentsRequest) GetFileId() *UUID {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *UpdateFileContentsRequest) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type UpdateFileContentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFileContentsResponse) Reset() {
	*x = UpdateFileContentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFileContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileContentsResponse) ProtoMessage() {}

func (x *UpdateFileContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileContentsResponse.ProtoReflect.Descriptor instead.
func (*UpdateFileContentsResponse) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{9}
}

type GetFileContentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey string `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// File to download.
	FileId *UUID `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *GetFileContentsRequest) Reset() {
	*x = GetFileContentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileContentsRequest) ProtoMessage() {}

func (x *GetFileContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileContentsRequest.ProtoReflect.Descriptor instead.
func (*GetFileContentsRequest) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileContentsRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *GetFileContentsRequest) GetFileId() *UUID {
	if x != nil {
		return x.FileId
	}
	return nil
}

type GetFileContentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contents of file. (If found)
	Contents []byte `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *GetFileContentsResponse) Reset() {
	*x = GetFileContentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileContentsResponse) ProtoMessage() {}

func (x *GetFileContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileContentsResponse.ProtoReflect.Descriptor instead.
func (*GetFileContentsResponse) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileContentsResponse) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type MoveObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey string `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// Object to move.
	ObjectId *UUID `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// Directory to move to.
	DirId *UUID `protobuf:"bytes,3,opt,name=dir_id,json=dirId,proto3" json:"dir_id,omitempty"`
	// New name of object.
	NewName string `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

func (x *MoveObjectRequest) Reset() {
	*x = MoveObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveObjectRequest) ProtoMessage() {}

func (x *MoveObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveObjectRequest.ProtoReflect.Descriptor instead.
func (*MoveObjectRequest) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{12}
}

func (x *MoveObjectRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *MoveObjectRequest) GetObjectId() *UUID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

func (x *MoveObjectRequest) GetDirId() *UUID {
	if x != nil {
		return x.DirId
	}
	return nil
}

func (x *MoveObjectRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type MoveObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This will be the new object ID
	// Assigned to the moved object.
	// NOTE : maybe object_id won't change on move..
	// We can decide this later.
	ObjectId *UUID `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
}

func (x *MoveObjectResponse) Reset() {
	*x = MoveObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveObjectResponse) ProtoMessage() {}

func (x *MoveObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveObjectResponse.ProtoReflect.Descriptor instead.
func (*MoveObjectResponse) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{13}
}

func (x *MoveObjectResponse) GetObjectId() *UUID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

type RemoveObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey string `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// Object to delete.
	ObjectId *UUID `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
}

func (x *RemoveObjectRequest) Reset() {
	*x = RemoveObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveObjectRequest) ProtoMessage() {}

func (x *RemoveObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveObjectRequest.ProtoReflect.Descriptor instead.
func (*RemoveObjectRequest) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveObjectRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *RemoveObjectRequest) GetObjectId() *UUID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

type RemoveObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveObjectResponse) Reset() {
	*x = RemoveObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_head_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveObjectResponse) ProtoMessage() {}

func (x *RemoveObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_head_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveObjectResponse.ProtoReflect.Descriptor instead.
func (*RemoveObjectResponse) Descriptor() ([]byte, []int) {
	return file_protos_head_proto_rawDescGZIP(), []int{15}
}

var File_protos_head_proto protoreflect.FileDescriptor

var file_protos_head_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64,
	0x22, 0x1c, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x68,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x28,
	0x0a, 0x06, 0x64, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x55, 0x55, 0x49,
	0x44, 0x52, 0x05, 0x64, 0x69, 0x72, 0x49, 0x64, 0x22, 0xc9, 0x01, 0x0a, 0x0a, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x6f,
	0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x08, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x68,
	0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a,
	0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x46,
	0x49, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x4f,
	0x52, 0x59, 0x10, 0x01, 0x22, 0x51, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68,
	0x65, 0x61, 0x64, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x7c, 0x0a, 0x14, 0x4d, 0x61, 0x6b, 0x65, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79,
	0x12, 0x28, 0x0a, 0x06, 0x64, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x55,
	0x55, 0x49, 0x44, 0x52, 0x05, 0x64, 0x69, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x69,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x69,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a, 0x15, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x06, 0x64, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x55, 0x55, 0x49,
	0x44, 0x52, 0x05, 0x64, 0x69, 0x72, 0x49, 0x64, 0x22, 0x97, 0x01, 0x0a, 0x11, 0x41, 0x64, 0x64,
	0x4e, 0x65, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12,
	0x28, 0x0a, 0x06, 0x64, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x55, 0x55,
	0x49, 0x44, 0x52, 0x05, 0x64, 0x69, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x40, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x6f, 0x74,
	0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x65, 0x49, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65,
	0x61, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x65, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68,
	0x65, 0x61, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64,
	0x22, 0x35, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x11, 0x4d, 0x6f, 0x76, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x2e,
	0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e,
	0x55, 0x55, 0x49, 0x44, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x28,
	0x0a, 0x06, 0x64, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x55, 0x55, 0x49,
	0x44, 0x52, 0x05, 0x64, 0x69, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x12, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68,
	0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52,
	0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x13, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65,
	0x61, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x8c, 0x05, 0x0a, 0x0d, 0x48, 0x6f,
	0x6f, 0x74, 0x46, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x28, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61,
	0x64, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e,
	0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x4d, 0x61, 0x6b, 0x65,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x68, 0x6f, 0x6f, 0x74,
	0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x68,
	0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4d, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1e,
	0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x41, 0x64, 0x64,
	0x4e, 0x65, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x41, 0x64, 0x64,
	0x4e, 0x65, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x65, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x26, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68,
	0x65, 0x61, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x68, 0x6f, 0x6f, 0x74,
	0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x1e, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61, 0x64,
	0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x20, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68, 0x65, 0x61,
	0x64, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2e, 0x68,
	0x65, 0x61, 0x64, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x6f, 0x74, 0x66, 0x73, 0x2f, 0x68, 0x6f,
	0x6f, 0x74, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_head_proto_rawDescOnce sync.Once
	file_protos_head_proto_rawDescData = file_protos_head_proto_rawDesc
)

func file_protos_head_proto_rawDescGZIP() []byte {
	file_protos_head_proto_rawDescOnce.Do(func() {
		file_protos_head_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_head_proto_rawDescData)
	})
	return file_protos_head_proto_rawDescData
}

var file_protos_head_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_head_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protos_head_proto_goTypes = []interface{}{
	(ObjectInfo_ObjectType)(0),           // 0: hootfs.head.ObjectInfo.ObjectType
	(*UUID)(nil),                         // 1: hootfs.head.UUID
	(*GetDirectoryContentsRequest)(nil),  // 2: hootfs.head.GetDirectoryContentsRequest
	(*ObjectInfo)(nil),                   // 3: hootfs.head.ObjectInfo
	(*GetDirectoryContentsResponse)(nil), // 4: hootfs.head.GetDirectoryContentsResponse
	(*MakeDirectoryRequest)(nil),         // 5: hootfs.head.MakeDirectoryRequest
	(*MakeDirectoryResponse)(nil),        // 6: hootfs.head.MakeDirectoryResponse
	(*AddNewFileRequest)(nil),            // 7: hootfs.head.AddNewFileRequest
	(*AddNewFileResponse)(nil),           // 8: hootfs.head.AddNewFileResponse
	(*UpdateFileContentsRequest)(nil),    // 9: hootfs.head.UpdateFileContentsRequest
	(*UpdateFileContentsResponse)(nil),   // 10: hootfs.head.UpdateFileContentsResponse
	(*GetFileContentsRequest)(nil),       // 11: hootfs.head.GetFileContentsRequest
	(*GetFileContentsResponse)(nil),      // 12: hootfs.head.GetFileContentsResponse
	(*MoveObjectRequest)(nil),            // 13: hootfs.head.MoveObjectRequest
	(*MoveObjectResponse)(nil),           // 14: hootfs.head.MoveObjectResponse
	(*RemoveObjectRequest)(nil),          // 15: hootfs.head.RemoveObjectRequest
	(*RemoveObjectResponse)(nil),         // 16: hootfs.head.RemoveObjectResponse
}
var file_protos_head_proto_depIdxs = []int32{
	1,  // 0: hootfs.head.GetDirectoryContentsRequest.dir_id:type_name -> hootfs.head.UUID
	1,  // 1: hootfs.head.ObjectInfo.object_id:type_name -> hootfs.head.UUID
	0,  // 2: hootfs.head.ObjectInfo.object_type:type_name -> hootfs.head.ObjectInfo.ObjectType
	3,  // 3: hootfs.head.GetDirectoryContentsResponse.objects:type_name -> hootfs.head.ObjectInfo
	1,  // 4: hootfs.head.MakeDirectoryRequest.dir_id:type_name -> hootfs.head.UUID
	1,  // 5: hootfs.head.MakeDirectoryResponse.dir_id:type_name -> hootfs.head.UUID
	1,  // 6: hootfs.head.AddNewFileRequest.dir_id:type_name -> hootfs.head.UUID
	1,  // 7: hootfs.head.AddNewFileResponse.file_id:type_name -> hootfs.head.UUID
	1,  // 8: hootfs.head.UpdateFileContentsRequest.file_id:type_name -> hootfs.head.UUID
	1,  // 9: hootfs.head.GetFileContentsRequest.file_id:type_name -> hootfs.head.UUID
	1,  // 10: hootfs.head.MoveObjectRequest.object_id:type_name -> hootfs.head.UUID
	1,  // 11: hootfs.head.MoveObjectRequest.dir_id:type_name -> hootfs.head.UUID
	1,  // 12: hootfs.head.MoveObjectResponse.object_id:type_name -> hootfs.head.UUID
	1,  // 13: hootfs.head.RemoveObjectRequest.object_id:type_name -> hootfs.head.UUID
	2,  // 14: hootfs.head.HootFsService.GetDirectoryContents:input_type -> hootfs.head.GetDirectoryContentsRequest
	5,  // 15: hootfs.head.HootFsService.MakeDirectory:input_type -> hootfs.head.MakeDirectoryRequest
	7,  // 16: hootfs.head.HootFsService.AddNewFile:input_type -> hootfs.head.AddNewFileRequest
	9,  // 17: hootfs.head.HootFsService.UpdateFileContents:input_type -> hootfs.head.UpdateFileContentsRequest
	11, // 18: hootfs.head.HootFsService.GetFileContents:input_type -> hootfs.head.GetFileContentsRequest
	13, // 19: hootfs.head.HootFsService.MoveObject:input_type -> hootfs.head.MoveObjectRequest
	15, // 20: hootfs.head.HootFsService.RemoveObject:input_type -> hootfs.head.RemoveObjectRequest
	4,  // 21: hootfs.head.HootFsService.GetDirectoryContents:output_type -> hootfs.head.GetDirectoryContentsResponse
	6,  // 22: hootfs.head.HootFsService.MakeDirectory:output_type -> hootfs.head.MakeDirectoryResponse
	8,  // 23: hootfs.head.HootFsService.AddNewFile:output_type -> hootfs.head.AddNewFileResponse
	10, // 24: hootfs.head.HootFsService.UpdateFileContents:output_type -> hootfs.head.UpdateFileContentsResponse
	12, // 25: hootfs.head.HootFsService.GetFileContents:output_type -> hootfs.head.GetFileContentsResponse
	14, // 26: hootfs.head.HootFsService.MoveObject:output_type -> hootfs.head.MoveObjectResponse
	16, // 27: hootfs.head.HootFsService.RemoveObject:output_type -> hootfs.head.RemoveObjectResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protos_head_proto_init() }
func file_protos_head_proto_init() {
	if File_protos_head_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_head_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirectoryContentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirectoryContentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeDirectoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeDirectoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFileContentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFileContentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileContentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileContentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_head_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_head_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_head_proto_goTypes,
		DependencyIndexes: file_protos_head_proto_depIdxs,
		EnumInfos:         file_protos_head_proto_enumTypes,
		MessageInfos:      file_protos_head_proto_msgTypes,
	}.Build()
	File_protos_head_proto = out.File
	file_protos_head_proto_rawDesc = nil
	file_protos_head_proto_goTypes = nil
	file_protos_head_proto_depIdxs = nil
}
